<?xml version="1.0" encoding="utf-8"?><Database Name="bd" Class="DCDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=C:\Users\Наташа\Desktop\kurs_bd\bd.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="kurs.Properties.Settings" SettingsPropertyName="bdConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Lessons" Member="Lessons">
    <Type Name="Lessons">
      <Column Name="Id_les" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="type_les" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="Lessons_Schedule" Member="Schedule" ThisKey="Id_les" OtherKey="lesID" Type="Schedule" />
      <Association Name="Lessons_Translate" Member="Translate" ThisKey="Id_les" OtherKey="lesID" Type="Translate" />
      <Association Name="Lessons_Mark" Member="Mark" ThisKey="Id_les" OtherKey="lesID" Type="Mark" />
    </Type>
  </Table>
  <Table Name="dbo.Practice" Member="Practice">
    <Type Name="Practice">
      <Column Name="Id_pr" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="practice" Member="practice1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="themeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Theme_Practice" Member="Theme" ThisKey="themeID" OtherKey="Id_theme" Type="Theme" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Schedule" Member="Schedule">
    <Type Name="Schedule">
      <Column Name="Id_sh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="day" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pair" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lesID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="relID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Lessons_Schedule" Member="Lessons" ThisKey="lesID" OtherKey="Id_les" Type="Lessons" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Subject" Member="Subject">
    <Type Name="Subject">
      <Column Name="Id_sub" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name_sub" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Subject_Theme" Member="Theme" ThisKey="Id_sub" OtherKey="subID" Type="Theme" />
      <Association Name="Subject_Translate" Member="Translate" ThisKey="Id_sub" OtherKey="subID" Type="Translate" />
      <Association Name="Subject_Mark" Member="Mark" ThisKey="Id_sub" OtherKey="subID" Type="Mark" />
      <Association Name="Subject_Group_Sub" Member="Group_Sub" ThisKey="Id_sub" OtherKey="subID" Type="Group_Sub" />
    </Type>
  </Table>
  <Table Name="dbo.Theme" Member="Theme">
    <Type Name="Theme">
      <Column Name="Id_theme" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name_theme" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="subID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Theme_Practice" Member="Practice" ThisKey="Id_theme" OtherKey="themeID" Type="Practice" />
      <Association Name="Theme_Theor_ques" Member="Theor_ques" ThisKey="Id_theme" OtherKey="themeID" Type="Theor_ques" />
      <Association Name="Subject_Theme" Member="Subject" ThisKey="subID" OtherKey="Id_sub" Type="Subject" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Theor_ques" Member="Theor_ques">
    <Type Name="Theor_ques">
      <Column Name="Id_q" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="qestion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="themeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Theme_Theor_ques" Member="Theme" ThisKey="themeID" OtherKey="Id_theme" Type="Theme" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Translate" Member="Translate">
    <Type Name="Translate">
      <Column Name="Id_trans" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="max_point" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[34point]" Member="_34point" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[45point]" Member="_45point" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="min_point" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="subID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lesID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Lessons_Translate" Member="Lessons" ThisKey="lesID" OtherKey="Id_les" Type="Lessons" IsForeignKey="true" />
      <Association Name="Subject_Translate" Member="Subject" ThisKey="subID" OtherKey="Id_sub" Type="Subject" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Type_answer" Member="Type_answer">
    <Type Name="Type_answer">
      <Column Name="Id_ans" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tanswer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="questID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Type_question_Type_answer" Member="Type_question" ThisKey="questID" OtherKey="Id_tq" Type="Type_question" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Type_question" Member="Type_question">
    <Type Name="Type_question">
      <Column Name="Id_tq" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tquestion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Type_question_Type_answer" Member="Type_answer" ThisKey="Id_tq" OtherKey="questID" Type="Type_answer" />
    </Type>
  </Table>
  <Table Name="dbo.Mark" Member="Mark">
    <Type Name="Mark">
      <Column Name="Id_mark" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="point" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date_p" Type="System.DateTimeOffset" DbType="DateTimeOffset" CanBeNull="true" />
      <Column Name="lesID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="studID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="subID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Lessons_Mark" Member="Lessons" ThisKey="lesID" OtherKey="Id_les" Type="Lessons" IsForeignKey="true" />
      <Association Name="Subject_Mark" Member="Subject" ThisKey="subID" OtherKey="Id_sub" Type="Subject" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Group_Sub" Member="Group_Sub">
    <Type Name="Group_Sub">
      <Column Name="Id_rel" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="groupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="subID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Subject_Group_Sub" Member="Subject" ThisKey="subID" OtherKey="Id_sub" Type="Subject" IsForeignKey="true" />
      <Association Name="Peopl_Group_Sub" Member="Peopl" ThisKey="groupID" OtherKey="Id_group" Type="Peopl" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Peopl" Member="Peopl">
    <Type Name="Peopl">
      <Column Name="Id_group" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name_group" Type="System.String" DbType="NChar(15) NOT NULL" CanBeNull="false" />
      <Association Name="Peopl_Group_Sub" Member="Group_Sub" ThisKey="Id_group" OtherKey="groupID" Type="Group_Sub" />
      <Association Name="Peopl_Student" Member="Student" ThisKey="Id_group" OtherKey="groupID" Type="Student" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Student">
    <Type Name="Student">
      <Column Name="Id_student" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FIO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="mail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="groupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Peopl_Student" Member="Peopl" ThisKey="groupID" OtherKey="Id_group" Type="Peopl" IsForeignKey="true" />
    </Type>
  </Table>
</Database>